Areas/Student/Controllers/MST_StudentController.cs
using CRUDDemo.Areas.Branch.Models;
using CRUDDemo.Areas.City.Models;
using CRUDDemo.Areas.Student.Models;
using Microsoft.AspNetCore.Mvc;
using System.Data;
using System.Data.SqlClient;

namespace CRUDDemo.Areas.Student.Controllers
{
    [Area("Student")]
    [Route("Student/[controller]/[action]")]

    public class MST_StudentController : Controller
    {
        private IConfiguration Configuration;
        public MST_StudentController(IConfiguration configuration)
        {
            Configuration = configuration;
        }


        #region SelectAll
        [Route("")]
        [Route("StudentList")]
        public IActionResult Index()
        {
            DataTable dt = new DataTable();
            string str = Configuration.GetConnectionString("myConnectionString");
            SqlConnection conn = new SqlConnection(str);
            conn.Open();
            SqlCommand cmd = conn.CreateCommand();
            cmd.CommandType = CommandType.StoredProcedure;
            cmd.CommandText = "PR_Mst_Student_SelectAll";
            SqlDataReader reader = cmd.ExecuteReader();

            if (reader.HasRows)
            {
                dt.Load(reader);
            }
            return View("MST_StudentList", dt);
        }
        #endregion

        #region SelectByPK

        public IActionResult Add(int? StudentID)
        {
            FillCityDDL();
            FillBranchDDL();
            if (StudentID != null)
            {
                SqlConnection objConn = new SqlConnection(this.Configuration.GetConnectionString("myConnectionString"));
                objConn.Open();
                SqlCommand objCmd = objConn.CreateCommand();
                objCmd.CommandType = CommandType.StoredProcedure;
                objCmd.CommandText = "PR_Mst_Student_SelectByPK";
                objCmd.Parameters.AddWithValue("@StudentID", StudentID);

                SqlDataReader objSDR = objCmd.ExecuteReader();

                MST_StudentModel student = new MST_StudentModel();

                if (objSDR.HasRows)
                {
                    while (objSDR.Read())
                    {
                        student.StudentName = objSDR["StudentName"].ToString();
                        student.BranchID = Convert.ToInt32(objSDR["BranchID"]);
                        student.CityID = Convert.ToInt32(objSDR["CityID"]);
                        student.MobileNoStudent = objSDR["MobileNoStudent"].ToString();
                        student.Email = objSDR["Email"].ToString();
                        student.MobileNoFather = objSDR["MobileNoFather"].ToString();
                        student.Address = objSDR["Address"].ToString();
                        student.BirthDate = Convert.ToDateTime(objSDR["BirthDate"]);
                        student.Age = Convert.ToInt32(objSDR["Age"]);
                        student.IsActive = Convert.ToBoolean(objSDR["IsActive"]);
                        student.Gender = objSDR["Gender"].ToString();
                        student.Password = objSDR["Password"].ToString();
                    }
                }
                return View("MST_StudentAddEdit", student);
            }
            return View("MST_StudentAddEdit");
        }
        #endregion

        #region ADD EDIT
        [HttpPost]
        public IActionResult Save(MST_StudentModel modelMST_Student)
        {
            if (ModelState.IsValid)
            {

                SqlConnection objConn = new
                SqlConnection(this.Configuration.GetConnectionString("myConnectionString"));
                objConn.Open();
                SqlCommand objCmd = objConn.CreateCommand();
                objCmd.CommandType = CommandType.StoredProcedure;
                if (modelMST_Student.StudentID == null)
                {
                    objCmd.CommandText = "PR_Mst_Student_Insert";
                    objCmd.Parameters.AddWithValue("@Created", DateTimeOffset.Now);
                }
                else
                {
                    objCmd.CommandText = "PR_Mst_Student_UpdateByPK";
                    objCmd.Parameters.AddWithValue("@StudentID", modelMST_Student.StudentID);
                }

                objCmd.Parameters.AddWithValue("@StudentName", modelMST_Student.StudentName);
                objCmd.Parameters.AddWithValue("@BranchID", modelMST_Student.BranchID);
                objCmd.Parameters.AddWithValue("@CityID", modelMST_Student.CityID);
                objCmd.Parameters.AddWithValue("@MobileNoStudent", modelMST_Student.MobileNoStudent);
                objCmd.Parameters.AddWithValue("@Email", modelMST_Student.Email);
                objCmd.Parameters.AddWithValue("@MobileNoFather", modelMST_Student.MobileNoFather);
                objCmd.Parameters.AddWithValue("@Address", modelMST_Student.Address);
                objCmd.Parameters.AddWithValue("@BirthDate", modelMST_Student.BirthDate);
                objCmd.Parameters.AddWithValue("@Age", modelMST_Student.Age);
                objCmd.Parameters.AddWithValue("@IsActive", modelMST_Student.IsActive);
                objCmd.Parameters.AddWithValue("@Gender", modelMST_Student.Gender);
                objCmd.Parameters.AddWithValue("@Password", modelMST_Student.Password);




                if (Convert.ToBoolean(objCmd.ExecuteNonQuery()))
                {
                    if (modelMST_Student.StudentID == null)
                        TempData["Message"] = " ";
                    else
                    {
                        TempData["Message"] = " ";
                        return RedirectToAction("Index");
                    }
                }
            }
            return RedirectToAction("Index");
        }


        #endregion


        #region DELETE
        [Route("Delete")]
        public IActionResult DeleteStudent(int StudentID)
        {
            Console.Write(StudentID);
            SqlConnection objConn = new SqlConnection(this.Configuration.GetConnectionString("myConnectionString"));
            objConn.Open();
            SqlCommand objCmd = objConn.CreateCommand();
            objCmd.CommandType = CommandType.StoredProcedure;
            objCmd.CommandText = "PR_Mst_Student_DeleteByPK ";
            objCmd.Parameters.Add("@StudentID", SqlDbType.Int).Value = StudentID;
            if (Convert.ToBoolean(objCmd.ExecuteNonQuery()))
            {
                TempData["Message"] = "Delete Successfully ";
            }
            objConn.Close();
            return RedirectToAction("Index");
        }

        #endregion

        #region Fill City DropDown
        public void FillCityDDL()
        {
            List<CityDropDownModel> list = new List<CityDropDownModel>();
            SqlConnection con = new SqlConnection(this.Configuration.GetConnectionString("myConnectionString"));
            con.Open();
            SqlCommand cmd = con.CreateCommand();
            cmd.CommandType = CommandType.StoredProcedure;
            cmd.CommandText = "PR_City_SelectAll";
            SqlDataReader dr = cmd.ExecuteReader();
            if (dr.HasRows)
            {
                while (dr.Read())
                {
                    CityDropDownModel cityDropDown = new CityDropDownModel()
                    {
                        CityID = Convert.ToInt32(dr["CityID"]),
                        CityName = dr["CityName"].ToString()
                    };
                    list.Add(cityDropDown);
                }
                dr.Close();
            }
            con.Close();
            ViewBag.CityList = list;
        }
        #endregion

        #region Fill Branch DropDown
        public void FillBranchDDL()
        {
            List<BranchDropDownModel> list = new List<BranchDropDownModel>();
            SqlConnection con = new SqlConnection(this.Configuration.GetConnectionString("myConnectionString"));
            con.Open();
            SqlCommand cmd = con.CreateCommand();
            cmd.CommandType = CommandType.StoredProcedure;
            cmd.CommandText = "PR_Mst_Branch_SelectAll";
            SqlDataReader dr = cmd.ExecuteReader();
            if (dr.HasRows)
            {
                while (dr.Read())
                {
                    BranchDropDownModel brancheDropDown = new BranchDropDownModel()
                    {
                        BranchID = Convert.ToInt32(dr["BranchID"]),
                        BranchName = dr["BranchName"].ToString()
                    };
                    list.Add(brancheDropDown);
                }
                dr.Close();
            }
            con.Close();
            ViewBag.BranchList = list;
        }
        #endregion

    }
}

Areas/Student/Views/MST_Student/MST_StudentAddEdit.cshtml
@{
    ViewData["Title"] = "Student Add/Edit";
}
@model CRUDDemo.Areas.Student.Models.MST_StudentModel

<div class="row">
    <div class="col-md-12">
        <h1>Add Student</h1>
        <form method="post" asp-area="Student" asp-controller="MST_Student" asp-action="Save">
            @Html.HiddenFor(x=>x.StudentID)
            <div class="form-group">
                <label for="StudentName">Student Name</label>
                <input type="text" asp-for="StudentName" placeholder="Enter Student Name" class="form-control" />
                <span asp-validation-for="StudentName" class="form-text text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <label for="MobileNoStudent">Student Mobile No</label>
                <input asp-for="MobileNoStudent" placeholder="Enter Student Mobile No" type="number" class="form-control">
                <span asp-validation-for="MobileNoStudent" class="form-text text-danger"></span>
            </div>
            <br />

            <div class="form-group">
                <label for="StudentEmail">Student Email</label>
                <input asp-for="Email" placeholder="Enter Student Email" type="email" class="form-control">
                <span asp-validation-for="Email" class="form-text text-danger"></span>
            </div>
            <br />

            <div class="form-group">
                <label for="FatherMobileNumber">Student Father Mobile No</label>
                <input asp-for="MobileNoFather" placeholder="Enter Father Student Mobile No" type="number" class="form-control">
                <span asp-validation-for="MobileNoFather" class="form-text text-danger"></span>
            </div>
            <br />

            <div class="form-group">
                <label for="BranchID">Branch</label>
                <div>
                    <select asp-for="BranchID" asp-items=@(new SelectList(ViewBag.BranchList,"BranchID","BranchName")) class="form-control custom-select">
                        <option disabled selected>Select Branch</option>
                    </select>
                    <span asp-validation-for="BranchID" class="form-text text-danger"></span>
                </div>
            </div>
            <br />

            <div class="form-group">
                <label for="CityID">City</label>
                <div>
                    <select asp-for="CityID" asp-items=@(new SelectList(ViewBag.CityList,"CityID","CityName")) class="form-control custom-select">
                        <option disabled selected>Select City</option>
                    </select>
                    <span asp-validation-for="CityID" class="form-text text-danger"></span>
                </div>
            </div>
            <br />

            <div class="form-group">
                <label for="Address">Student Address</label>
                <input asp-for="Address" placeholder="Enter Student Address " type="text" class="form-control">
                <span asp-validation-for="Address" class="form-text text-danger"></span>
            </div>
            <br />

            <div class="form-group">
                <label for="BirthDate">Birth Date</label>
                <input asp-for="BirthDate" placeholder="Enter Birth Date" type="date" class="form-control">
                <span asp-validation-for="BirthDate" class="form-text text-danger"></span>
            </div>
            <br />

            <div class="form-group">
                <label for="Age">Age</label>
                <input asp-for="Age" placeholder="Enter Student Age " type="Text" class="form-control">
                <span asp-validation-for="Age" class="form-text text-danger"></span>
            </div>

            <br />

            <div class="form-group">
                <label for="IsActive">Status</label><br />
                @Html.CheckBoxFor(x => x.IsActive)<span>IsActive</span>
            </div>

            <div class="form-group">
                <label for="Gender">Gender</label><br />
                @Html.RadioButtonFor(x => x.Gender,"Male")Male
                @Html.RadioButtonFor(x => x.Gender,"Female")Female
            </div>

            <br />

            <div class="form-group">
                <label for="Password">Password</label>
                <input asp-for="Password" placeholder="Enter Password " type="password" class="form-control">
                <span asp-validation-for="Password" class="form-text text-danger"></span>
            </div>
            <hr />

            <div class="form-group">
                <button type="submit" class="btn btn-success" asp-area="Student" asp-action="Save" asp-controller="MST_Student" onclick="MSg()">Save</button>
                <a name="cancel" type="reset" class="btn btn-danger" asp-area="Student" asp-action="StudentAddEdit" asp-controller="MST_Student">Cancel</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("~/Views/Shared/_ValidationScriptsPartial.cshtml");
    }
    <script type="text/javascript">

        function MSg() {
            const id = document.getElementById("StudentID").value;

            if (id == '') {
                alert("Record Inserted Successfully");
            }
            else {
                alert("Record Updated Successfully");
            }
        }
    </script>
}

Areas/Student/Views/MST_Student/MST_StudentList.cshtml
@using System.Data;
@{
    ViewData["Title"] = "Student List";
}

@model DataTable
<div class="card">
    <div class="card-body">
        <a class="btn btn-success btn-sm mb-1" asp-area="Student" asp-controller="MST_Student" asp-action="Add">
            Add Student
        </a>
        <div class="table-responsive">
            <table class="table">
                <thead>
                    <tr>

                        <th>StudentName</th>
                        <th>BranchName</th>
                        <th>CityName</th>
                        <th>StudentNumber</th>
                        <th>Email</th>
                        <th>FatherNumber</th>
                        <th>Address</th>
                        <th>BirthDate</th>
                        <th>Age</th>
                        <th>Gender</th>
                        <th>IsActive</th>
                        <th>Password</th>
                        <th>Created</th>
                        <th>Modified</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    @if (Model.Rows.Count > 0)
                    {
                        foreach (DataRow dr in Model.Rows)
                        {
                            <tr>
                                <td>@dr["StudentName"]</td>
                                <td>@dr["BranchName"]</td>
                                <td>@dr["CityName"]</td>
                                <td>@dr["MobileNoStudent"]</td>
                                <td>@dr["Email"]</td>
                                <td>@dr["MobileNoFather"]</td>
                                <td>@dr["Address"]</td>
                                <td>@Convert.ToDateTime(dr["BirthDate"]).ToString("dd-MM-yyyy")</td>
                                <td>@dr["Age"]</td>
                                <td>@dr["Gender"]</td>
                                <td>@dr["IsActive"]</td>
                                <td>@dr["Password"]</td>
                                <td>@Convert.ToDateTime(dr["Created"]).ToString("dd-MM-yyyy")</td>
                                <td>@Convert.ToDateTime(dr["Modified"]).ToString("dd-MM-yyyy")</td>

                                <td>
                                    <form method="post" asp-area="Student" asp-controller="MST_Student" asp-action="DeleteStudent">
                                        <input type="hidden" name="StudentID" value="@dr["StudentID"]">
                                        <div class="btn-group" role="group" aria-label="Basic example">
                                            <button type="submit" class="btn btn-danger btn-sm me-2" onclick="return confirmDelete();">
                                                Delete
                                            </button>
                                            <a class="btn btn-primary btn-sm" asp-area="Student" asp-controller="MST_Student" asp-action="Add" asp-route-StudentID="@dr["StudentID"]">
                                                Edit
                                            </a>
                                        </div>
                                    </form>
                                </td>
                            </tr>
                        }
                    }
                    else
                    {
                        <tr>
                            <th colspan="4" class="text-center">
                                No Record Found.
                            </th>
                        </tr>
                    }

                </tbody>
            </table>
        </div>
    </div>
</div>
@section Scripts
    {
    <script type="text/javascript">
        function confirmDelete() {
            if (confirm("Are you sure you want to delete this Student?")) {
                return true;
            }
            else {
                return false;
            }
        }
    </script>
}