Areas/Branch/Controllers/MST_BranchController.cs
using CRUDDemo.Areas.Branch.Models;
using Microsoft.AspNetCore.Mvc;
using System.Data;
using System.Data.SqlClient;

namespace CRUDDemo.Areas.Branch.Controllers
{
    [Area("Branch")]
    [Route("MST_Branch/[controller]/[action]")]
    public class MST_BranchController : Controller
    {
        private IConfiguration Configuration;
        public MST_BranchController(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        #region Select All

        public IActionResult Index()
        {
            DataTable dt = new DataTable();
            string str = Configuration.GetConnectionString("myConnectionString");
            SqlConnection conn = new SqlConnection(str);
            conn.Open();
            SqlCommand cmd = conn.CreateCommand();
            cmd.CommandType = CommandType.StoredProcedure;
            cmd.CommandText = "PR_Mst_Branch_SelectAll";
            SqlDataReader dr = cmd.ExecuteReader();

            if (dr.HasRows)
            {
                dt.Load(dr);
            }
            return View("MST_BranchList", dt);
        }
        #endregion

        #region SelectByPK
        public ActionResult Add(int? BranchID)
        {
            if (BranchID != null)
            {
                string str = Configuration.GetConnectionString("myConnectionString");
                SqlConnection conn = new SqlConnection(str);
                conn.Open();
                SqlCommand cmd = conn.CreateCommand();
                cmd.CommandType = CommandType.StoredProcedure;
                cmd.CommandText = "PR_Mst_Branch_SelectByPK";

                cmd.Parameters.Add("@BranchID", SqlDbType.Int).Value = BranchID;
                DataTable dt = new DataTable();
                SqlDataReader dr = cmd.ExecuteReader();
                MST_BranchModel branch = new MST_BranchModel();
                if (dr.Read())
                {


                    branch.BranchName = dr["BranchName"].ToString();
                    branch.BranchCode = dr["BranchCode"].ToString();

                }
                return View("MST_BranchAddEdit", branch);
            }
            return View("MST_BranchAddEdit");
        }


        #endregion

        #region Add Edit
        [HttpPost]
        public IActionResult Save(MST_BranchModel modelMST_Branch)
        {
            string str = Configuration.GetConnectionString("myConnectionString");
            SqlConnection conn = new SqlConnection(str);
            conn.Open();
            SqlCommand cmd = conn.CreateCommand();
            cmd.CommandType = CommandType.StoredProcedure;

            if (modelMST_Branch.BranchID == null)
            {
                cmd.CommandText = "PR_Mst_Branch_Insert";
                cmd.Parameters.AddWithValue("@Created", DateTimeOffset.Now);
            }
            else
            {
                cmd.CommandText = "PR_Mst_Branch_UpdateByPK";
                cmd.Parameters.Add("@BranchID", SqlDbType.Int).Value = modelMST_Branch.BranchID;
            }
            cmd.Parameters.Add("@BranchName", SqlDbType.VarChar).Value = modelMST_Branch.BranchName;
            cmd.Parameters.Add("@BranchCode", SqlDbType.VarChar).Value = modelMST_Branch.BranchCode;

            if (Convert.ToBoolean(cmd.ExecuteNonQuery()))
            {
                if (modelMST_Branch.BranchID == null)
                {
                    TempData["BranchInsertMsg"] = "";
                }
                else
                {
                    TempData["BranchInsertMsg"] = "";
                    return RedirectToAction("Index");
                }
            }
            conn.Close();

            return RedirectToAction("Index");
        }
        #endregion

        #region Delete
        [Route("DeleteBranch")]
        public IActionResult DeleteBranch(int branchID)
        {
            SqlConnection conn = new SqlConnection(this.Configuration.GetConnectionString("myConnectionString"));
            conn.Open();
            SqlCommand sqlcommand = conn.CreateCommand();
            sqlcommand.CommandType = CommandType.StoredProcedure;
            sqlcommand.CommandText = "PR_Mst_Branch_DeleteByPK";
            sqlcommand.Parameters.Add("@BranchID", SqlDbType.Int).Value = branchID;
            if (Convert.ToBoolean(sqlcommand.ExecuteNonQuery()))
            {
                TempData["Message"] = " ";
            }
            conn.Close();
            return RedirectToAction("Index");
        }
        #endregion

    }
}

Areas/Branch/Views/MST_Branch/MST_BranchAddEdit.cshtml
@{
    ViewData["Title"] = "Branch Add/Edit";
}

@model CRUDDemo.Areas.Branch.Models.MST_BranchModel

<div class="row">
    <div class="col-md-12">
        <h3>@TempData["BranchInsertMsg"]</h3>
        <form method="post" asp-action="save" asp-controller="MST_Branch" asp-area="Branch">
            <div class="form-group">
                @Html.HiddenFor(x=>x.BranchID)
                <label>Branch Name</label>
                <input type="text" class="form-control" asp-for="BranchName" />
                <span asp-validation-for="BranchName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label>Branch Code</label>
                <input type="text" class="form-control" asp-for="BranchCode " />
                <span asp-validation-for="BranchCode" class="text-danger"></span>
            </div>
            <hr />
            <button type="submit" class="btn btn-primary" asp-action="Save" asp-controller="MST_Branch" asp-area="Branch" id="" onclick="MSg()">Save</button>
            <a class="btn btn-danger" asp-controller="MST_Branch" asp-action="Index">Cancel</a>
        </form>
    </div>
</div>


@section Scripts {
    @{
        await Html.RenderPartialAsync("~/Views/Shared/_ValidationScriptsPartial.cshtml");
    }

    <script type="text/javascript">

        function MSg() {
            const id = document.getElementById("BranchID").value;

            if (id == '') {
                alert("Record Inserted Successfully");

            }
            else {
                alert("Record Updated Successfully");
            }

        }
    </script>

}

Areas/Branch/Views/MST_Branch/MST_BranchList.cshtml
@using System.Data

@{
    ViewData["Title"] = "Branch List";
}

@model DataTable

<a asp-action="Add" asp-controller="MST_Branch" asp-area="Branch" class="btn btn-primary btn-sm">Add Branch</a>
<table class="table">
    <thead>
        <tr>
            <th>Branch name</th>
            <th>Branch Code</th>
            <th>Created</th>
            <th>Modified</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        @if (Model.Rows.Count > 0)
        {
            foreach (DataRow dr in Model.Rows)
            {
                <tr>
                    <td>@dr["BranchName"]</td>
                    <td>@dr["BranchCode"]</td>
                    <td>@Convert.ToDateTime(dr["Created"]).ToString("dd-MM-yyyy")</td>
                    <td>@Convert.ToDateTime(dr["Modified"]).ToString("dd-MM-yyyy")</td>
                    <td>
                        <form method="post" asp-area="Branch" asp-controller="MST_Branch" asp-action="DeleteBranch">
                            <input type="hidden" name="BranchID" value="@dr["BranchID"]">
                            <button type="submit" class="btn btn-danger btn-sm me-2" onclick="return confirmDelete();">Delete</button>
                            <a asp-action="Add" asp-controller="MST_Branch" asp-area="Branch" asp-route-BranchID="@dr["BranchID"]" class="btn btn-primary btn-sm">Edit</a>
                        </form>
                    </td>
                </tr>
            }
        }
        else
        {
            <tr>
                <td colspan="6">
                    <p class="col-form-label">No Record Found</p>
                </td>
            </tr>
        }
    </tbody>
</table>

@section Scripts
    {
    <script type="text/javascript">
        function confirmDelete() {
            if (confirm("Are you sure you want to delete this Branch?")) {
                return true;
            }
            else {
                return false;
            }
        }
    </script>
}