Areas/City/Controllers/LOC_CityController.cs
using CRUDDemo.Areas.City.Models;
using CRUDDemo.Areas.Country.Models;
using CRUDDemo.Areas.State.Models;
using Microsoft.AspNetCore.Mvc;
using System.Data;
using System.Data.SqlClient;

namespace CRUDDemo.Areas.City.Controllers
{
    [Area("City")]
    [Route("City/[controller]/[action]")]
    public class LOC_CityController : Controller
    {
        private IConfiguration Configuration;
        public LOC_CityController(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        #region SelectAll
        public IActionResult Index()
        {
            DataTable dt = new DataTable();
            string str = Configuration.GetConnectionString("myConnectionString");
            SqlConnection conn = new SqlConnection(str);
            conn.Open();
            SqlCommand cmd = conn.CreateCommand();
            cmd.CommandType = CommandType.StoredProcedure;
            cmd.CommandText = "PR_City_SelectAll";
            SqlDataReader dr = cmd.ExecuteReader();

            if (dr.HasRows)
            {
                dt.Load(dr);
            }
            return View("LOC_CityList", dt);
        }
        #endregion

        #region SelectByPK
        public IActionResult Add(int? CityID)
        {
            FillCountryDDL();
            FillStateDDL();

            if (CityID != null)
            {
                String str = Configuration.GetConnectionString("myConnectionString");
                SqlConnection conn = new SqlConnection(str);
                conn.Open();
                SqlCommand cmd = conn.CreateCommand();
                cmd.CommandType = CommandType.StoredProcedure;
                cmd.CommandText = "PR_City_SelectByPK";

                cmd.Parameters.Add("@CityID", SqlDbType.Int).Value = CityID;
                DataTable dt = new DataTable();
                SqlDataReader reader = cmd.ExecuteReader();
                LOC_CityModel city = new LOC_CityModel();
                if (reader.Read())
                {
                    city.CityName = reader["CityName"].ToString();
                    city.CityCode = reader["CityCode"].ToString();
                    city.StateID = Convert.ToInt32(reader["StateID"]);
                    city.CountryID = Convert.ToInt32(reader["CountryID"]);

                }
                return View("LOC_CityAddEdit", city);
            }
            return View("LOC_CityAddEdit");
        }
        #endregion

        #region Add Edit

        [HttpPost]
        public IActionResult Save(LOC_CityModel modelLOC_City)
        {
            if (ModelState.IsValid)
            {
                string str = Configuration.GetConnectionString("myConnectionString");
                SqlConnection conn = new SqlConnection(str);
                conn.Open();
                SqlCommand cmd = conn.CreateCommand();
                cmd.CommandType = CommandType.StoredProcedure;

                if (modelLOC_City.CityID == null)
                {
                    cmd.CommandText = "PR_City_Insert";
                    cmd.Parameters.AddWithValue("@CreationDate", DateTimeOffset.Now);
                }
                else
                {
                    cmd.CommandText = "PR_City_UpdateByPK";
                    cmd.Parameters.Add("@CityID", SqlDbType.Int).Value = modelLOC_City.CityID;
                }
                cmd.Parameters.Add("@CityName", SqlDbType.VarChar).Value = modelLOC_City.CityName;
                cmd.Parameters.Add("@CityCode", SqlDbType.VarChar).Value = modelLOC_City.CityCode;
                cmd.Parameters.Add("@StateID", SqlDbType.Int).Value = modelLOC_City.StateID;
                cmd.Parameters.Add("@CountryID", SqlDbType.Int).Value = modelLOC_City.CountryID;

                if (Convert.ToBoolean(cmd.ExecuteNonQuery()))
                {
                    if (modelLOC_City.CityID == null)

                        TempData["CityInsertMsg"] = " ";
                    else
                    {
                        TempData["CityInsertMsg"] = "";
                        return RedirectToAction("Index");
                    }
                }
                conn.Close();
            }

            return RedirectToAction("Index");
        }
        #endregion

        #region Delete
        [Route("DeleteCountry")]
        public IActionResult Delete(int CityID)
        {
            SqlConnection conn = new SqlConnection(this.Configuration.GetConnectionString("myConnectionString"));
            conn.Open();
            SqlCommand sqlcommand = conn.CreateCommand();
            sqlcommand.CommandType = CommandType.StoredProcedure;
            sqlcommand.CommandText = "PR_City_DeleteByPK";
            sqlcommand.Parameters.Add("@CityID", SqlDbType.Int).Value = CityID;
            if (Convert.ToBoolean(sqlcommand.ExecuteNonQuery()))
            {
                TempData["Message"] = " ";
            }
            conn.Close();
            return RedirectToAction("Index");
        }
        #endregion

        #region FilStateDDL
        public void FillStateDDL()
        {
            List<StateDropDownModel> list = new List<StateDropDownModel>();
            SqlConnection con = new SqlConnection(this.Configuration.GetConnectionString("myConnectionString"));
            con.Open();
            SqlCommand cmd = con.CreateCommand();
            cmd.CommandType = CommandType.StoredProcedure;
            cmd.CommandText = "PR_State_SelectAll";
            SqlDataReader dr = cmd.ExecuteReader();
            if (dr.HasRows)
            {
                while (dr.Read())
                {
                    StateDropDownModel state = new StateDropDownModel()
                    {
                        StateID = Convert.ToInt32(dr["StateID"]),
                        StateName = dr["StateName"].ToString()
                    };
                    list.Add(state);
                }
                dr.Close();
            }
            con.Close();
            ViewBag.StateList = list;
        }
        #endregion

        #region FillCountryDDL
        public void FillCountryDDL()
        {
            List<LOC_CountryDropDownModel> list = new List<LOC_CountryDropDownModel>();
            SqlConnection con = new SqlConnection(this.Configuration.GetConnectionString("myConnectionString"));
            con.Open();
            SqlCommand cmd = con.CreateCommand();
            cmd.CommandType = CommandType.StoredProcedure;
            cmd.CommandText = "PR_Country_SelectAll";
            SqlDataReader dr = cmd.ExecuteReader();
            if (dr.HasRows)
            {
                while (dr.Read())
                {
                    LOC_CountryDropDownModel country = new LOC_CountryDropDownModel()
                    {
                        CountryID = Convert.ToInt32(dr["CountryID"]),
                        CountryName = dr["CountryName"].ToString()
                    };
                    list.Add(country);
                }
                dr.Close();
            }
            con.Close();
            ViewBag.CountryList = list;
        }
        #endregion

    }
}

Areas/City/Views/LOC_City/LOC_CityAddEdit.cshtml
@{
    ViewData["Title"] = "City Add/Edit";
}
@model CRUDDemo.Areas.City.Models.LOC_CityModel

<div class="row">
    <div class="row">
        <div class="col-md-12">
            <h3>@TempData["CityInsertMsg"]</h3>
            <form method="post" asp-action="Save" asp-controller="LOC_City" asp-area="City">

                <div class="form-group">
                    <label for="CountryID">Country</label>
                    <div>
                        <select asp-for="CountryID" asp-items=@(new SelectList(ViewBag.CountryList,"CountryID","CountryName")) class="form-control custom-select">
                            <option disabled selected>Select Country</option>
                        </select>
                        <span asp-validation-for="CountryID" class="form-text text-danger"></span>
                    </div>
                </div>

                <div class="form-group">
                    <label for="StateID">State</label>
                    <div>
                        <select asp-for="StateID" asp-items=@(new SelectList(ViewBag.StateList,"StateID","StateName")) class="form-control custom-select">
                            <option disabled selected>Select State</option>
                        </select>
                        <span asp-validation-for="StateID" class="form-text text-danger"></span>
                    </div>
                </div>
                <div class="form-group">
                    @Html.HiddenFor(x=>x.CityID)
                    <label>City Name</label>
                    <input type="text" class="form-control" asp-for="CityName" />
                    <span asp-validation-for="CityName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label>City Code</label>
                    <input type="text" class="form-control" asp-for="CityCode " />
                    <span asp-validation-for="CityCode" class="text-danger"></span>
                </div>
                <hr />
                <button type="submit" class="btn btn-primary" id="" asp-area="City" asp-controller="LOC_City" asp-action="Save" onclick="MSg()">Save</button>
                <a class="btn btn-danger" asp-controller="LOC_City" asp-action="Index">Cancel</a>
            </form>
        </div>
    </div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("~/Views/Shared/_ValidationScriptsPartial.cshtml");
    }

        <script type="text/javascript">

            function MSg() {
                const id = document.getElementById("StateID").value;

                if (id == '') {
                    alert("Record Inserted Successfully");

                }
                else {
                    alert("Record Updated Successfully");
                }

            }
        </script>

}

Areas/City/Views/LOC_City/LOC_CityList.cshtml
@{
	ViewData["Title"] = "City List";
}

@using System.Data;
@model DataTable;


<a asp-action="Add" asp-controller="LOC_City" asp-area="City" class="btn btn-primary btn-sm">Add City</a>
<table class="table">
    <thead>
        <tr>
            <th>City name</th>
            <th>State Name</th>
            <th>Country Name</th>
            <th>City Code</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        @{
            if (Model.Rows.Count > 0)
            {
                foreach (DataRow dr in Model.Rows)
                {
                    <tr>
                        <td>@dr["CityName"]</td>
                        <td>@dr["StateName"]</td>
                        <td>@dr["CountryName"]</td>
                        <td>@dr["CityCode"]</td>
                        <td>
                            <form method="post" asp-area="City" asp-controller="LOC_City" asp-action="Delete">
                                <input type="hidden" name="CityID" value="@dr["CityID"]">
                                <button type="submit" class="btn btn-danger btn-sm me-2" onclick="return confirmDelete();">Delete</button>
                                <a asp-action="Add" asp-controller="LOC_City" asp-area="City" asp-route-CityID="@dr["CityID"]" class="btn btn-primary btn-sm">Edit</a>
                            </form>
                        </td>
                    </tr>
                }
            }
            else
            {
                <tr>
                    <td colspan="6">
                        <p class="col-form-label">No Record Found</p>
                    </td>
                </tr>
            }
        }
    </tbody>
</table>
@section Scripts
    {
    <script type="text/javascript">
        function confirmDelete() {
            if (confirm("Are you sure you want to delete this City?")) {
                return true;
            }
            else {
                return false;
            }
        }
    </script>
}