Areas/State/Controllers/LOC_StateController.cs
using CRUDDemo.Areas.Country.Models;
using CRUDDemo.Areas.State.Models;
using Microsoft.AspNetCore.Mvc;
using System.Data;
using System.Data.SqlClient;

namespace CRUDDemo.Areas.State.Controllers
{
    [Area("State")]
    [Route("State/[controller]/[action]")]

    public class LOC_StateController : Controller
    {
        private readonly IConfiguration Configuration;

        public LOC_StateController(IConfiguration _configuration)
        {
            Configuration = _configuration;
        }

        #region Select All State
        public IActionResult Index()
        {
            DataTable dt = new DataTable();
            string str = Configuration.GetConnectionString("myConnectionString");
            SqlConnection conn = new SqlConnection(str);
            conn.Open();
            SqlCommand cmd = conn.CreateCommand();
            cmd.CommandType = CommandType.StoredProcedure;
            cmd.CommandText = "PR_State_selectAll";
            SqlDataReader dr = cmd.ExecuteReader();

            if (dr.HasRows)
            {
                dt.Load(dr);
            }
            conn.Close();
            return View("LOC_StateList", dt);
        }
        #endregion

        #region Delete
        [Route("DeleteState")]
        public IActionResult DeleteState(int StateID)
        {
            SqlConnection conn = new SqlConnection(this.Configuration.GetConnectionString("myConnectionString"));
            conn.Open();
            SqlCommand sqlcommand = conn.CreateCommand();
            sqlcommand.CommandType = CommandType.StoredProcedure;
            sqlcommand.CommandText = "PR_State_DeleteByPK";
            sqlcommand.Parameters.Add("@StateID", SqlDbType.Int).Value = StateID;
            if (Convert.ToBoolean(sqlcommand.ExecuteNonQuery()))
            {
                TempData["Message"] = " ";
            }
            conn.Close();
            return RedirectToAction("Index");
        }
        #endregion

        #region select by primaryKey

        public IActionResult AddEdit(int? StateID)
        {
            FillCountryDDL();
            if (StateID != null)
            {
                string str = Configuration.GetConnectionString("myConnectionString");
                SqlConnection conn = new SqlConnection(str);
                conn.Open();
                SqlCommand cmd = conn.CreateCommand();
                cmd.CommandType = CommandType.StoredProcedure;
                cmd.CommandText = "PR_State_SelectByPK";
                cmd.Parameters.Add("@StateID", SqlDbType.Int).Value = StateID;
                DataTable dt = new DataTable();
                SqlDataReader dr = cmd.ExecuteReader();
                LOC_StateModel state = new LOC_StateModel();
                if (dr.Read())
                {


                    state.StateName = dr["StateName"].ToString();
                    state.StateCode = dr["StateCode"].ToString();
                    state.CountryID = Convert.ToInt32(dr["CountryID"]);

                }
                return View("LOC_StateAddEdit", state);
            }
            return View("LOC_StateAddEdit");
        }
        #endregion

        #region Add Edit
        [HttpPost]
        public IActionResult Save(LOC_StateModel model_LOC_State)
        {
            if (ModelState.IsValid)
            {
                SqlConnection objConn = new
                SqlConnection(this.Configuration.GetConnectionString("myConnectionString"));
                objConn.Open();
                SqlCommand objCmd = objConn.CreateCommand();
                objCmd.CommandType = CommandType.StoredProcedure;
                if (model_LOC_State.StateID == null)
                {
                    objCmd.CommandText = "PR_State_Insert";
                    objCmd.Parameters.AddWithValue("@Created", DateTimeOffset.Now);
                }
                else
                {
                    objCmd.CommandText = "PR_State_UpdateByPK";
                    objCmd.Parameters.AddWithValue("@StateID", model_LOC_State.StateID);
                }
                objCmd.Parameters.AddWithValue("@StateName", model_LOC_State.StateName);
                objCmd.Parameters.AddWithValue("@StateCode", model_LOC_State.StateCode);
                objCmd.Parameters.AddWithValue("@CountryID", model_LOC_State.CountryID);

                if (Convert.ToBoolean(objCmd.ExecuteNonQuery()))
                {
                    if (model_LOC_State.StateID == null)
                        TempData["StateInsertMsg"] = " ";
                    else
                    {
                        TempData["StateInsertMsg"] = " ";
                        return RedirectToAction("Index");
                    }
                }
                objConn.Close();
            }
            return RedirectToAction("Index");
        }

        #endregion


        #region fillCountryDDL
        public void FillCountryDDL()
        {
            List<LOC_CountryDropDownModel> list = new List<LOC_CountryDropDownModel>();
            SqlConnection con = new SqlConnection(this.Configuration.GetConnectionString("myConnectionString"));
            con.Open();
            SqlCommand cmd = con.CreateCommand();
            cmd.CommandType = CommandType.StoredProcedure;
            cmd.CommandText = "PR_Country_SelectAll";
            SqlDataReader dr = cmd.ExecuteReader();
            if (dr.HasRows)
            {
                while (dr.Read())
                {
                    LOC_CountryDropDownModel countryDropDown = new LOC_CountryDropDownModel()
                    {
                        CountryID = Convert.ToInt32(dr["CountryID"]),
                        CountryName = dr["CountryName"].ToString()
                    };
                    list.Add(countryDropDown);
                }
                dr.Close();
            }
            con.Close();
            ViewBag.CountryList = list;
        }
        #endregion


    }
}

Areas/State/Views/LOC_State/LOC_StateAddEdit.cshtml
@{
    ViewData["Title"] = "State Add/Edit";
}
<h1>StateAddEdit</h1>
@model CRUDDemo.Areas.State.Models.LOC_StateModel

<hr />

<div class="row">
    <div class="col-md-12">
        <h3>@TempData["StateInsertMsg"]</h3>
        <form method="post" asp-action="Save" asp-controller="LOC_State" asp-area="State">

            <div class="form-group">
                <label for="CountryID">Country</label>
                <div>
                    <select asp-for="CountryID" asp-items=@(new SelectList(ViewBag.CountryList,"CountryID","CountryName")) class="form-control custom-select">
                        <option disabled selected>Select Country</option>
                    </select>
                    <span asp-validation-for="CountryID" class="form-text text-danger"></span>
                </div>
            </div>
            <div class="form-group">
                @Html.HiddenFor(x=>x.StateID)
                <label>State Name</label>
                <input type="text" class="form-control" asp-for="StateName" />
                <span asp-validation-for="StateName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label>State Code</label>
                <input type="text" class="form-control" asp-for="StateCode " />
                <span asp-validation-for="StateCode" class="text-danger"></span>
            </div>
            <hr />
            <button type="submit" class="btn btn-primary" id="" asp-area="State" asp-controller="LOC_State" asp-action="Save" onclick="MSg()">Save</button>
            <a class="btn btn-danger" asp-controller="LOC_State" asp-action="Index">Cancel</a>
        </form>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("~/Views/Shared/_ValidationScriptsPartial.cshtml");
    }

    <script type="text/javascript">

        function MSg() {
            const id = document.getElementById("StateID").value;

            if (id == '') {
                alert("Record Inserted Successfully");

            }
            else {
                alert("Record Updated Successfully");
            }

        }
    </script>

}

Areas/State/Views/LOC_State/LOC_StateList.cshtml
@{
	ViewData["Title"] = "State List";
}

@using System.Data;
@model DataTable;

<a asp-action="AddEdit" asp-controller="LOC_State" asp-area="State" class="btn btn-primary btn-sm">Add State</a>
<table class="table">
    <tr>
        <th>State name</th>
        <th>State Code</th>
        <th>Country name</th>
        <th>Creation</th>
        <th>Modified</th>
        <th>Action</th>
    </tr>
    <tbody>

        @if (Model.Rows.Count > 0)
        {
            foreach (DataRow dr in Model.Rows)
            {
                <tr>
                    <td>@dr["StateName"]</td>
                    <td>@dr["StateCode"]</td>
                    <td>@dr["CountryName"]</td>
                    <td>@Convert.ToDateTime(dr["Created"]).ToString("dd-MM-yyyy")</td>
                    <td>@Convert.ToDateTime(dr["Modified"]).ToString("dd-MM-yyyy")</td>
                    <td>
                        <form method="post" asp-area="State" asp-controller="LOC_State" asp-action="DeleteState">
                            <input type="hidden" name="StateID" value="@dr["StateID"]">
                            <button type="submit" class="btn btn-danger btn-sm me-2" onclick="return confirmDelete();">Delete</button>
                            <a class="btn btn-primary btn-sm" asp-action="AddEdit" asp-controller="LOC_State" asp-area="State" asp-route-StateID="@dr["StateID"]">Edit</a>
                        </form>

                    </td>
                </tr>
            }
        }
        else
        {
            <tr>
                <td colspan="6">
                    <p class="col-form-label">No Record Found</p>
                </td>
            </tr>
        }
    </tbody>
</table>

@section Scripts
    {
    <script type="text/javascript">
        function confirmDelete() {
            if (confirm("Are you sure you want to delete this State?")) {
                return true;
            }
            else {
                return false;
            }
        }
    </script>
}